### PR TITLE
Revamp the databroker search widget

### PR DESCRIPTION
**Pull request by danielballan**
This is a complete overhaul of the databroker search widget.

## User-facing changes

* Previously, the UI made hard assumptions about the catalog. It was expected to have a specific level of nesting: to be a catalog of catalogs of BlueskyRuns. Now, the UI supports digging into arbitrarily nested catalogs---e.g. root > NSLS-II > CSX > analysis results.
* The app is more responsive while search results load. If the user scrolls faster than results can be loaded and displayed, the cells of the table are filled with a placeholder, "...", and soon filled in.
* The search results do not update automatically. Instead there is a Refresh button. This is in line with good UI practice: it's disruptive when a list or table of items shifts under you as you about to click something. We could in the future add a notification that a refresh is needed / more results are available, such as in the GitHub notifications UI or Twitter.
* The "Custom Query" input field and the Summary Widget have been removed. It would easy to restore them, but we might find better uses for that screen real estate.

## Screenshots

First, select a subcatalog.

image

A catalog has been selected. The model detects that this is a catalog of `BlueskyRun`s so it adds a search input and results. (If this were a more nested catalog, there would be more drop-down boxes first.) You can use the Back button to select a different catalog.

image

Clicking on a result shows an image preview. (I tested this with real user data from FXI but I don't have permission to post a screenshot of that data.) Selecting result(s) and clicking open prints the associated `BlueskyRun` in the console.

## Internal Changes

* To populate the search results, we had previously used `setData()`, which is intended for _editing_ tables, not progressively loading them. With some help from @hhslepicka and @cryos I think this is now making correct use of Qt's model--view. As mentioned on Slack, we defer row-appending using `fetchMore()` in the standard way. To populate the _contents_ of the rows in a way that doesn't weigh down the event loop, we do something clever in `data()`. The first call to `data()` immediately returns a placeholder but, as a side effect, adds some work to queue. A worker thread takes work from the queue, does the blocking I/O to get the actual content, updates a cache, and finally calls dataChanged() to redraw the specific cells that need to be redrawn. When Qt executes that redraw, it calls `data()` a second time and hits that cache.
* The core functionality is imported from [bluesky-widgets](http://blueskyproject.io/bluesky-widgets), added as a dependency in this PR. It has no required dependencies itself, so no additional secondary dependencies are introduced.
* The model encapsulated in the object `Search` can be used to do anything you would do from the GUI---move in and out of subcatalogs, change search parameters, etc. This may be useful to initialize the GUI in a desired state, and also for "headless" functionality.

## Testing

* The components imported from bluesky-widgets are unit tested there.
* I did an informal integration test by browsing search results from CSX and RSOXS catalogs. These large catalogs loaded smoothly.

## Questions

* Is it OK to drop the custom query input?
* Is it OK to shed the Summary Widget? Do we want a replacement/successor as part of this PR? If so, what should it include?
* Is there any other functionality that the original had grown that I failed to retain here?

### CODE REVIEW

**Comment by danielballan** [comment]
Checklist from call with @ronpandolfi:

- [x] Handle thread cleanup more cleanly: https://github.com/bluesky/bluesky-widgets/pull/4, https://github.com/bluesky/bluesky-widgets/pull/10
- [ ] Re-instate a free-form query input field (perhaps in a modal dialog, to preserve a clean UI) https://github.com/bluesky/bluesky-widgets/issues/12
- [ ] Add more ergonomic time input, such as "Last 24 Hours" https://github.com/bluesky/bluesky-widgets/issues/8

**Comment by danielballan** [comment]
This now relies on unreleased changed to bluesky-widgets (related to how threading is handled). Needs a bluesky-widgets release and update to requirements.txt before merging.

**Comment by birdzix** [comment]
@danielballan The changes to threading (as you addressed with bluesky/bluesky-widgets#4, bluesky/bluesky-widgets#10) look great. As far as UI changes go, I think it is alright to defer re-implementing a query widget (bluesky/bluesky-widgets#12) and the more user-friendly time input (bluesky/bluesky-widgets#8) for now and can be integrated with a later update to bluesky-widgets.
I appreciate the time you spent to do all of this, provide screenshots, and perform your own integration test. I tested your branch on my end and it worked great!

Regarding merging this PR, @ronpandolfi do you have any thoughts?

(Also, I'm curious if the threading changes fix issues with ```test_application.py``` segfaulting as well)

**Review by ronpandolfi — APPROVED** [review]
Approved pending https://github.com/bluesky/bluesky-widgets/pull/14

**Comment by danielballan** [comment]
bluesky/bluesky-widgets#14 merged and released in v0.0.3. Minimum version bumped in 98fe9be.

This is ready for merge.

**Comment by danielballan** [comment]
:tada:

**Pull request merged**
