### PR TITLE
Fix Stream/FieldSelector mixins

### PR DESCRIPTION
**Pull request by ronpandolfi**
Set stream name earlier so that CatalogViewer knows which stream to inspect for the data when the field list is updated.

### CODE REVIEW

**Comment by dylanmcreynolds** [comment]
The fix looks good. While were in this code, I wanted to move CatalogViewer over to using bluesky_utils, which required a commit. I'll create another pr in CatalogViewer for the move over.

**Comment by dylanmcreynolds** [comment]
This PR has another problem (well, probably not this PR, but another potential issue that was introduced with this refactor.) Prior to the refactor that created FieldSelector, the Catalog Viewer limited the list of fields to those that had a chance of being displayed:

`if field_shape > 1 and field_shape < 5:`

This no longer happens. Using data from CSX (darkframe-example), we see that all 20+ fields are displayed, when only fccd_image is really going to show. This is because imageviewmixins.FieldSelector.updateFieldNames() is what now actually populates the combo box and it does no filtering.

Is this intentional? If so we can leave it. But I suspect that it's a regression to fix.

I would advocate adding a method in bluesky_utils something like 
`def is_field_displayable():`

This could then be called in both get_all_image_fields and imageviewmixins.FieldSelector.updateFieldNames() to decide how to filter for displayable fields.

**Comment by dylanmcreynolds** [comment]
You know, another thing that's been lost is the clearing of the image when the use changes the run, stream or field. I found this to be a really nice feature. If things go well, then the user is clued in to the fact that the system is responding to their action (even if loading isn't immediate.) And it's misleading to leave the old image up when there was an error painting the new image.

**Comment by ronpandolfi** [comment]
The lack of filtering _is_ a regression; I planned to come back to it at a later point, but we can address it now. I wanted to add some additional flexibility, allowing the filter to be configurable. I like the structure you described, `is_field_displayable()` would serve as a sensible default.

I wasn't aware of the clearing. I'll add that in here as well.

**Review by dylanmcreynolds — COMMENTED** [review]
Looks great.

**Pull request merged**
